@startuml
|Клиент|
start
:Клиент вошел в систему;

repeat
    :Клиент перешел к списку экспертов;
    :Клиент выбрал эксперта;
    if (Эксперт выбран?) then (нет)
        break        
    else (да)
        :Отображение доступного времени эксперта;
        repeat
            :Клиент выбирает время консультации;
            if (Время выбрано?) then (нет)
                break
            else (да)
                |Система|
                :Создание записи на консультацию;
                :Запрос на оплату;
                |Внешняя система оплаты|
                :Обработка платежа;
                if (Платеж подтвержден?) then (да)
                    |Система|
                    :Сохранение записи о консультации;
                    :Отправка уведомлений пользователю и эксперту;
                    |Клиент|
                    :Получение подтверждения записи;
                    stop
                else (нет)
                    :Уведомление об ошибке оплаты;
                    break
                endif                
            endif
        repeat while (Время не выбрано)
        
    endif
repeat while (Консульация выбрана и оплачена?)
stop
@enduml
